### ISSUE TITLE
Функциональные требования 

### ISSUE THREAD

**Issue by dratdin** [Igor-Losev-450502/BeFriend#1]
Я так понимаю, при старте викторины ты будешь генерировать вопросы, было бы неплохо увидеть данный пункт в функциональных требованиях, также ты говорил о таблице лучших игроков это также было бы неплохо увидеть в функциональных требованиях. В целом идея прикольная. Круто, что она задействует друзей из вк и интересно будет проверить насколько ты знаешь того или иного человека 👍

**Comment by Igor-Losev-450502** [comment]
Да, все верно подмечено. Уже исправил, спасибо!
